package log.summer.aigc.loop;

import log.summer.aigc.port.BotMessage;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Component;

import java.util.*;

/**
 * Resolves placeholder values in LLM-generated tool arguments
 * with actual binary data from the inbound BotMessage.
 *
 * <p>Supported placeholders:
 * <ul>
 *   <li><code>${message.image}</code> &rarr; byte[] from msg.imageBytes()</li>
 *   <li><code>${message.file}</code> &rarr; byte[] from msg.fileBytes()</li>
 *   <li><code>${message.fileName}</code> &rarr; String from msg.fileName()</li>
 * </ul>
 */
@Slf4j
@Component
public class ArgumentResolver {

    private static final String IMAGE_PLACEHOLDER = "${message.image}";
    private static final String FILE_PLACEHOLDER = "${message.file}";
    private static final String FILE_NAME_PLACEHOLDER = "${message.fileName}";

    /**
     * Walk all argument values and replace placeholder strings with actual data.
     *
     * @param rawArgs the arguments generated by the LLM
     * @param msg     the original inbound message carrying binary data
     * @return resolved arguments ready for tool execution
     */
    public Map<String, Object> resolve(Map<String, Object> rawArgs, BotMessage msg) {
        Map<String, Object> resolved = new LinkedHashMap<>(rawArgs);

        for (Map.Entry<String, Object> entry : resolved.entrySet()) {
            Object value = entry.getValue();
            if (value instanceof String str) {
                switch (str) {
                    case IMAGE_PLACEHOLDER -> {
                        if (msg.hasImage()) {
                            entry.setValue(msg.imageBytes());
                        } else {
                            throw new PlaceholderResolutionException(
                                    "LLM referenced ${message.image} but no image in current message");
                        }
                    }
                    case FILE_PLACEHOLDER -> {
                        if (msg.hasFile()) {
                            entry.setValue(msg.fileBytes());
                        } else {
                            throw new PlaceholderResolutionException(
                                    "LLM referenced ${message.file} but no file in current message");
                        }
                    }
                    case FILE_NAME_PLACEHOLDER -> {
                        if (msg.fileName() != null) {
                            entry.setValue(msg.fileName());
                        } else {
                            throw new PlaceholderResolutionException(
                                    "LLM referenced ${message.fileName} but no fileName in current message");
                        }
                    }
                }
            }
        }

        return resolved;
    }

    /**
     * Thrown when a placeholder cannot be resolved.
     * Caught by AgentLoop &rarr; produces ActResult.failure &rarr; LLM self-corrects.
     */
    public static class PlaceholderResolutionException extends RuntimeException {
        public PlaceholderResolutionException(String message) {
            super(message);
        }
    }
}
